language: node_js

sudo: required

services:
  - docker

node_js:
  - "5"

install:
  - cd ./back

   # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # npm install for build
  - npm install

  # build, babel
  - npm run build

  # build docker image
  - npm run build:updater

  - cd ..

script:
    - cd ./back
    # run unit test for back
    - npm test

    ## push the docker image to registry
    # login to hub.docker
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

    # push
    - docker push platane/paris-velib-updater
    - cd ..


# env:
#   - NODE_ENV=production
