language: node_js

sudo: required

services:
  - docker

node_js:
  - "5"

install:
  - cd ./back

   # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # npm install for build
  - npm install

  # build, babel
  - npm run build

  # build docker image
  - npm run build:updater

  - cd ..

script:
    # run unit test for back
    - cd ./back
    - npm test
    - cd ..

# env:
#   - NODE_ENV=production
